apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# BNG Blaster DHCP test: L2 DHCP with veth pair
resources:
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: bng-edge
      app.kubernetes.io/component: blaster-test
