apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - charts/kube-state-metrics/templates/clusterrolebinding.yaml
  - charts/kube-state-metrics/templates/deployment.yaml
  - charts/kube-state-metrics/templates/role.yaml
  - charts/kube-state-metrics/templates/service.yaml
  - charts/kube-state-metrics/templates/serviceaccount.yaml
  - charts/prometheus-node-exporter/templates/daemonset.yaml
  - charts/prometheus-node-exporter/templates/service.yaml
  - charts/prometheus-node-exporter/templates/serviceaccount.yaml
  - charts/prometheus-pushgateway/templates/deployment.yaml
  - charts/prometheus-pushgateway/templates/service.yaml
  - charts/prometheus-pushgateway/templates/serviceaccount.yaml
  - templates/clusterrole.yaml
  - templates/clusterrolebinding.yaml
  - templates/cm.yaml
  - templates/deploy.yaml
  - templates/service.yaml
  - templates/serviceaccount.yaml
