apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - rbac.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/name: nexus
      app.kubernetes.io/component: nexus-p2p
