apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: metrics
      port: 9002
      targetPort: 9002
    - name: p2p
      port: 33123
      targetPort: 33123
  clusterIP: None  # Headless for StatefulSet
  selector:
    app: nexus
