apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# HA with shared Nexus test: two BNGs with common state
resources:
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: bng-edge
      app.kubernetes.io/component: ha-nexus-test
