apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/clusterrole.yaml
  - templates/clusterrolebinding.yaml
  - templates/configmap.yaml
  - templates/dashboards-json-configmap.yaml
  - templates/deployment.yaml
  - templates/role.yaml
  - templates/rolebinding.yaml
  - templates/secret.yaml
  - templates/service.yaml
  - templates/serviceaccount.yaml
