apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus-rules.yaml

configMapGenerator:
  - name: grafana-dashboards-bng
    files:
      - grafana-dashboards/bng-overview.json
    options:
      labels:
        grafana_dashboard: "1"
